'use client';

import { useFood } from '@/components/food-provider';
import { AddIngredient } from './components/add-ingredient';
import Carousel from './components/carousel';
import FetchRecipes from './components/fetch-recipes';
import Footer from './components/footer';
const elements: Meal[] = [
  {
    strMeal: 'Beef Lo Mein',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/1529444830.jpg',
    idMeal: '52952',
    recipeDetail: {
      idMeal: '52952',
      strMeal: 'Beef Lo Mein',
      strMealAlternate: null,
      strCategory: 'Beef',
      strArea: 'Chinese',
      strInstructions: `STEP 1 - MARINATING THE BEEF
In a bowl, add the beef, salt, 1 pinch white pepper, 1 Teaspoon sesame seed oil, 1/2 egg, corn starch,1 Tablespoon of oil and mix together.
STEP 2 - BOILING THE THE NOODLES
In a 6 qt pot add your noodles to boiling water until the noodles are submerged and boil on high heat for 10 seconds. After your noodles is done boiling strain and cool with cold water.
STEP 3 - STIR FRY
Add 2 Tablespoons of oil, beef and cook on high heat untill beef is medium cooked.
Set the cooked beef aside
In a wok add 2 Tablespoon of oil, onions, minced garlic, minced ginger, bean sprouts, mushrooms, peapods and 1.5 cups of water or until the vegetables are submerged in water.
Add the noodles to wok
To make the sauce, add oyster sauce, 1 pinch white pepper, 1 teaspoon sesame seed oil, sugar, and 1 Teaspoon of soy sauce.
Next add the beef to wok and stir-fry`,
      strMealThumb:
        'https://www.themealdb.com/images/media/meals/1529444830.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=ZT9LSsNXXe0',
      strIngredient1: 'Beef',
      strIngredient2: 'Salt',
      strIngredient3: 'Pepper',
      strIngredient4: 'Sesame Seed Oil',
      strIngredient5: 'Egg',
      strIngredient6: 'Starch',
      strIngredient7: 'Oil',
      strIngredient8: 'Noodles',
      strIngredient9: 'Onion',
      strIngredient10: 'Minced Garlic',
      strIngredient11: 'Ginger',
      strIngredient12: 'Bean Sprouts',
      strIngredient13: 'Mushrooms',
      strIngredient14: 'Water',
      strIngredient15: 'Oyster Sauce',
      strIngredient16: 'Sugar',
      strIngredient17: 'Soy Sauce',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1/2 lb',
      strMeasure2: 'pinch',
      strMeasure3: 'pinch',
      strMeasure4: '2 tsp',
      strMeasure5: '1/2 ',
      strMeasure6: '3 tbs',
      strMeasure7: '5 tbs',
      strMeasure8: '1/4 lb',
      strMeasure9: '1/2 cup ',
      strMeasure10: '1 tsp ',
      strMeasure11: '1 tsp ',
      strMeasure12: '1 cup ',
      strMeasure13: '1 cup ',
      strMeasure14: '1 cup ',
      strMeasure15: '1 tbs',
      strMeasure16: '1 tsp ',
      strMeasure17: '1 tsp ',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'https://sueandgambo.com/pages/beef-lo-mein',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    ingredients: [
      'Beef',
      'Salt',
      'Pepper',
      'Sesame Seed Oil',
      'Egg',
      'Starch',
      'Oil',
      'Noodles',
      'Onion',
      'Minced Garlic',
      'Ginger',
      'Bean Sprouts',
      'Mushrooms',
      'Water',
      'Oyster Sauce',
      'Sugar',
      'Soy Sauce',
    ],
    userIngredientPresent: ['egg'],
    match: 6,
    nbrMissingIngredients: 16,
    measures: [
      '1/2 lb',
      'pinch',
      'pinch',
      '2 tsp',
      '1/2 ',
      '3 tbs',
      '5 tbs',
      '1/4 lb',
      '1/2 cup ',
      '1 tsp ',
      '1 tsp ',
      '1 cup ',
      '1 cup ',
      '1 cup ',
      '1 tbs',
      '1 tsp ',
      '1 tsp ',
    ],
  },
  {
    strMeal: 'Blini Pancakes',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/0206h11699013358.jpg',
    idMeal: '53080',
    recipeDetail: {
      idMeal: '53080',
      strMeal: 'Blini Pancakes',
      strMealAlternate: null,
      strCategory: 'Side',
      strArea: 'Russian',
      strInstructions: `In a large bowl, whisk together 1/2 cup buckwheat flour, 2/3 cup all-purpose flour, 1/2 teaspoon salt, and 1 teaspoon yeast.

Make a well in the center and pour in 1 cup warm milk, whisking until the batter is smooth.

Cover the bowl and let the batter rise until doubled, about 1 hour.

Enrich and Rest the Batter
Stir 2 tablespoons melted butter and 1 egg yolk into the batter.

In a separate bowl, whisk 1 egg white until stiff, but not dry.

Fold the whisked egg white into the batter.

Cover the bowl and let the batter stand 20 minutes.

Pan-Fry the Blini
Heat butter in a large nonstick skillet over medium heat.

Drop quarter-sized dollops of batter into the pan, being careful not to overcrowd the pan. Cook for about 1 minute or until bubbles form.

Turn and cook for about 30 additional seconds.

Remove the finished blini onto a plate and cover them with a clean kitchen towel to keep warm. Add more butter to the pan and repeat the frying process with the remaining batter.`,
      strMealThumb:
        'https://www.themealdb.com/images/media/meals/0206h11699013358.jpg',
      strTags: 'Pancake',
      strYoutube: 'https://www.youtube.com/watch?v=GsB8ZI5vREA',
      strIngredient1: 'Buckwheat',
      strIngredient2: 'Flour',
      strIngredient3: 'Salt',
      strIngredient4: 'Yeast',
      strIngredient5: 'Milk',
      strIngredient6: 'Butter',
      strIngredient7: 'Egg',
      strIngredient8: '',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1/2 cup ',
      strMeasure2: '2/3 Cup',
      strMeasure3: '1/2 tsp',
      strMeasure4: '1 tsp ',
      strMeasure5: '1 cup ',
      strMeasure6: '2 tbs',
      strMeasure7: '1 Seperated',
      strMeasure8: ' ',
      strMeasure9: ' ',
      strMeasure10: ' ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource:
        'https://www.thespruceeats.com/russian-blini-recipe-buckwheat-pancakes-1136797',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    ingredients: [
      'Buckwheat',
      'Flour',
      'Salt',
      'Yeast',
      'Milk',
      'Butter',
      'Egg',
    ],
    userIngredientPresent: ['egg'],
    match: 14,
    nbrMissingIngredients: 6,
    measures: [
      '1/2 cup ',
      '2/3 Cup',
      '1/2 tsp',
      '1 tsp ',
      '1 cup ',
      '2 tbs',
      '1 Seperated',
    ],
  },
  {
    strMeal: 'Boxty Breakfast',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/naqyel1608588563.jpg',
    idMeal: '53036',
    recipeDetail: {
      idMeal: '53036',
      strMeal: 'Boxty Breakfast',
      strMealAlternate: null,
      strCategory: 'Pork',
      strArea: 'Irish',
      strInstructions: `STEP 1
Before you start, put your oven on its lowest setting, ready to keep things warm. Peel the potatoes, grate 2 of them, then set aside. Cut the other 2 into large chunks, then boil for 10-15 mins or until tender. Meanwhile, squeeze as much of the liquid from the grated potatoes as you can using a clean tea towel. Mash the boiled potatoes, then mix with the grated potato, spring onions and flour.

STEP 2
Whisk the egg white in a large bowl until it holds soft peaks. Fold in the buttermilk, then add the bicarbonate of soda. Fold into the potato mix.

STEP 3
Heat a large non-stick frying pan over a medium heat, then add 1 tbsp butter and some of the oil. Drop 3-4 spoonfuls of the potato mixture into the pan, then gently cook for 3-5 mins on each side until golden and crusty. Keep warm on a plate in the oven while you cook the next batch, adding more butter and oil to the pan before you do so. You will get 16 crumpet-size boxty from the mix. Can be made the day ahead, drained on kitchen paper, then reheated in a low oven for 20 mins.

STEP 4
Heat the grill to medium and put the tomatoes in a heavy-based pan. Add a good knob of butter and a little oil, then fry for about 5 mins until softened. Grill the bacon, then pile onto a plate and keep warm. Stack up the boxty, bacon and egg, and serve the tomatoes on the side.`,
      strMealThumb:
        'https://www.themealdb.com/images/media/meals/naqyel1608588563.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=80W0mCFDIP0',
      strIngredient1: 'Potatoes',
      strIngredient2: 'Spring Onions',
      strIngredient3: 'Plain Flour',
      strIngredient4: 'Egg White',
      strIngredient5: 'Milk',
      strIngredient6: 'Bicarbonate Of Soda',
      strIngredient7: 'Butter',
      strIngredient8: 'Vegetable Oil',
      strIngredient9: 'Cherry Tomatoes',
      strIngredient10: 'Bacon',
      strIngredient11: 'Egg',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '4 large',
      strMeasure2: '1  bunch',
      strMeasure3: '100g ',
      strMeasure4: '1',
      strMeasure5: '150ml',
      strMeasure6: '1 tsp ',
      strMeasure7: '3 tbs',
      strMeasure8: '2 tbs',
      strMeasure9: '6',
      strMeasure10: '12',
      strMeasure11: '6',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource:
        'https://www.bbcgoodfood.com/recipes/boxty-bacon-eggs-tomatoes',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    ingredients: [
      'Potatoes',
      'Spring Onions',
      'Plain Flour',
      'Egg White',
      'Milk',
      'Bicarbonate Of Soda',
      'Butter',
      'Vegetable Oil',
      'Cherry Tomatoes',
      'Bacon',
      'Egg',
    ],
    userIngredientPresent: ['egg'],
    match: 9,
    nbrMissingIngredients: 10,
    measures: [
      '4 large',
      '1  bunch',
      '100g ',
      '1',
      '150ml',
      '1 tsp ',
      '3 tbs',
      '2 tbs',
      '6',
      '12',
      '6',
    ],
  },
  {
    strMeal: 'Bread omelette',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/hqaejl1695738653.jpg',
    idMeal: '53076',
    recipeDetail: {
      idMeal: '53076',
      strMeal: 'Bread omelette',
      strMealAlternate: null,
      strCategory: 'Breakfast',
      strArea: 'Indian',
      strInstructions: 'Make and enjoy',
      strMealThumb:
        'https://www.themealdb.com/images/media/meals/hqaejl1695738653.jpg',
      strTags: null,
      strYoutube: '',
      strIngredient1: 'Bread',
      strIngredient2: 'Egg',
      strIngredient3: 'Salt',
      strIngredient4: '',
      strIngredient5: '',
      strIngredient6: '',
      strIngredient7: '',
      strIngredient8: '',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '2',
      strMeasure2: '2',
      strMeasure3: '0.5',
      strMeasure4: ' ',
      strMeasure5: ' ',
      strMeasure6: ' ',
      strMeasure7: ' ',
      strMeasure8: ' ',
      strMeasure9: ' ',
      strMeasure10: ' ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: '',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    ingredients: ['Bread', 'Egg', 'Salt'],
    userIngredientPresent: ['egg'],
    match: 33,
    nbrMissingIngredients: 2,
    measures: ['2', '2', '0.5'],
  },
  {
    strMeal: 'Chick-Fil-A Sandwich',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/sbx7n71587673021.jpg',
    idMeal: '53016',
    recipeDetail: {
      idMeal: '53016',
      strMeal: 'Chick-Fil-A Sandwich',
      strMealAlternate: null,
      strCategory: 'Chicken',
      strArea: 'American',
      strInstructions: `Wrap the chicken loosely between plastic wrap and pound gently with the flat side of a meat tenderizer until about 1/2 inch thick all around.
Cut into two pieces, as even as possible.
Marinate in the pickle juice for 30 minutes to one hour (add a teaspoon of Tabasco sauce now for a spicy sandwich).
Beat the egg with the milk in a bowl.
Combine the flour, sugar, and spices in another bowl.
Dip the chicken pieces each into the egg on both sides, then coat in flour on both sides.
Heat the oil in a skillet (1/2 inch deep) to about 345-350.
Fry each cutlet for 2 minutes on each side, or until golden and cooked through.
Blot on paper and serve on toasted buns with pickle slices.`,
      strMealThumb:
        'https://www.themealdb.com/images/media/meals/sbx7n71587673021.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=1WDesu7bUDM',
      strIngredient1: 'Chicken Breast',
      strIngredient2: 'Pickle Juice',
      strIngredient3: 'Egg',
      strIngredient4: 'Milk',
      strIngredient5: 'Flour',
      strIngredient6: 'Icing Sugar',
      strIngredient7: 'Paprika',
      strIngredient8: 'Salt',
      strIngredient9: 'Black Pepper',
      strIngredient10: 'Garlic Powder',
      strIngredient11: 'Celery Salt',
      strIngredient12: 'Cayenne Pepper',
      strIngredient13: 'Olive Oil',
      strIngredient14: 'Sesame Seed Burger Buns',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1',
      strMeasure2: '1/4 cup',
      strMeasure3: '1',
      strMeasure4: '1/4 cup',
      strMeasure5: '1/2 cup ',
      strMeasure6: '1 tbs',
      strMeasure7: '1/2 tsp',
      strMeasure8: '1/2 tsp',
      strMeasure9: '1/4 tsp',
      strMeasure10: '1/4 tsp',
      strMeasure11: '1/4 tsp',
      strMeasure12: '1/2 tsp',
      strMeasure13: '1 cup ',
      strMeasure14: '1',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://hilahcooking.com/chick-fil-a-copycat/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    ingredients: [
      'Chicken Breast',
      'Pickle Juice',
      'Egg',
      'Milk',
      'Flour',
      'Icing Sugar',
      'Paprika',
      'Salt',
      'Black Pepper',
      'Garlic Powder',
      'Celery Salt',
      'Cayenne Pepper',
      'Olive Oil',
      'Sesame Seed Burger Buns',
    ],
    userIngredientPresent: ['egg'],
    match: 7,
    nbrMissingIngredients: 13,
    measures: [
      '1',
      '1/4 cup',
      '1',
      '1/4 cup',
      '1/2 cup ',
      '1 tbs',
      '1/2 tsp',
      '1/2 tsp',
      '1/4 tsp',
      '1/4 tsp',
      '1/4 tsp',
      '1/2 tsp',
      '1 cup ',
      '1',
    ],
  },
  {
    strMeal: 'Chivito uruguayo',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/n7qnkb1630444129.jpg',
    idMeal: '53063',
    recipeDetail: {
      idMeal: '53063',
      strMeal: 'Chivito uruguayo',
      strMealAlternate: null,
      strCategory: 'Beef',
      strArea: 'Uruguayan',
      strInstructions: `Crush the meat so that it is finite and we put it on a griddle to brown. Put the eggs, bacon and ham to fry.
Cut the bread in half, put the beef brisket, the fried eggs, the bacon, the ham, the mozzarella, the tomato and the lettuce. Cover with the other half of the bread and serve.`,
      strMealThumb:
        'https://www.themealdb.com/images/media/meals/n7qnkb1630444129.jpg',
      strTags: null,
      strYoutube:
        'https://www.youtube.com/watch?v=0PXbbL1QdaA&ab_channel=D%C3%ADadeCocina',
      strIngredient1: 'Beef Brisket',
      strIngredient2: 'Bread',
      strIngredient3: 'Lettuce',
      strIngredient4: 'Tomato',
      strIngredient5: 'Ham',
      strIngredient6: 'Mozzarella',
      strIngredient7: 'Bacon',
      strIngredient8: 'Egg',
      strIngredient9: 'Onion',
      strIngredient10: 'Pepper',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '2',
      strMeasure2: '2',
      strMeasure3: '1',
      strMeasure4: '1',
      strMeasure5: '100g ',
      strMeasure6: '100g ',
      strMeasure7: '100g ',
      strMeasure8: '1',
      strMeasure9: '1',
      strMeasure10: '1',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://cookpad.com/uy/recetas/116102-chivito-uruguayo',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    ingredients: [
      'Beef Brisket',
      'Bread',
      'Lettuce',
      'Tomato',
      'Ham',
      'Mozzarella',
      'Bacon',
      'Egg',
      'Onion',
      'Pepper',
    ],
    userIngredientPresent: ['egg'],
    match: 10,
    nbrMissingIngredients: 9,
    measures: ['2', '2', '1', '1', '100g ', '100g ', '100g ', '1', '1', '1'],
  },
  {
    strMeal: 'Flamiche',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/wssvvs1511785879.jpg',
    idMeal: '52906',
    recipeDetail: {
      idMeal: '52906',
      strMeal: 'Flamiche',
      strMealAlternate: null,
      strCategory: 'Vegetarian',
      strArea: 'French',
      strInstructions: `For the pastry, sift the flour and salt into the bowl of a food processor, add the butter and lard, then whizz together briefly until the mixture looks like fine breadcrumbs. Tip the mixture into a bowl, then stir in the cheese and enough of the water for the mixture to come together. Tip out onto a lightly floured surface and knead briefly until smooth. Roll out thinly and line a 23cm x 4cm loose-?bottomed fluted flan tin. Prick the base with a fork. Chill for 20 minutes.
02.Melt the 75g butter in a saucepan over a low heat, then add the leeks and the salt. Cover and cook for ?10 minutes until soft. Uncover the pan, increase the heat and cook ?for 2 minutes, stirring occasionally, until the liquid has evaporated. Spoon onto a plate and leave to cool.
03.Preheat the oven to 200°C/fan180°C/gas 6. Line the pastry case with baking paper and baking beans or rice and blind bake for 15-20 minutes until the edges are biscuit-coloured. Remove the paper and beans/rice and return the case to the oven for 7-10 minutes until the base is crisp and lightly golden. Remove and set aside. Reduce the oven temperature to 190°C/fan170°C/gas 5.
04.Put the crème fraîche into a bowl with the whole egg, egg yolks and nutmeg. Lightly beat together, then season. Stir in the leeks. Spoon ?the mixture into the tart case and bake for 35-40 minutes until set ?and lightly golden. Remove from ?the oven and leave for 10 minutes. Take out of the tin and serve.`,
      strMealThumb:
        'https://www.themealdb.com/images/media/meals/wssvvs1511785879.jpg',
      strTags: 'Tart',
      strYoutube: 'https://www.youtube.com/watch?v=vT0q5c880Rg',
      strIngredient1: 'Butter',
      strIngredient2: 'Leek',
      strIngredient3: 'Salt',
      strIngredient4: 'Creme Fraiche',
      strIngredient5: 'Egg',
      strIngredient6: 'Egg Yolks',
      strIngredient7: 'Nutmeg',
      strIngredient8: 'Plain Flour',
      strIngredient9: 'Salt',
      strIngredient10: 'Butter',
      strIngredient11: 'Lard',
      strIngredient12: 'Cheddar Cheese',
      strIngredient13: 'Water',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '75g',
      strMeasure2: '1kg',
      strMeasure3: '½ tsp',
      strMeasure4: '300ml ',
      strMeasure5: '1',
      strMeasure6: '3',
      strMeasure7: '¼ teaspoon',
      strMeasure8: '225g',
      strMeasure9: '½ tsp',
      strMeasure10: '60g',
      strMeasure11: '60g',
      strMeasure12: '50g',
      strMeasure13: '2 tbs',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource:
        'http://www.deliciousmagazine.co.uk/recipes/flamiche-flemish-leek-tart/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    ingredients: [
      'Butter',
      'Leek',
      'Salt',
      'Creme Fraiche',
      'Egg',
      'Egg Yolks',
      'Nutmeg',
      'Plain Flour',
      'Salt',
      'Butter',
      'Lard',
      'Cheddar Cheese',
      'Water',
    ],
    userIngredientPresent: ['egg'],
    match: 8,
    nbrMissingIngredients: 12,
    measures: [
      '75g',
      '1kg',
      '½ tsp',
      '300ml ',
      '1',
      '3',
      '¼ teaspoon',
      '225g',
      '½ tsp',
      '60g',
      '60g',
      '50g',
      '2 tbs',
    ],
  },
  {
    strMeal: 'General Tsos Chicken',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/1529444113.jpg',
    idMeal: '52951',
    recipeDetail: {
      idMeal: '52951',
      strMeal: 'General Tsos Chicken',
      strMealAlternate: null,
      strCategory: 'Chicken',
      strArea: 'Chinese',
      strInstructions: `DIRECTIONS:
STEP 1 - SAUCE
In a bowl, add 2 Cups of water, 2 Tablespoon soy sauce, 2 Tablespoon white vinegar, sherry cooking wine, 1/4 Teaspoon white pepper, minced ginger, minced garlic, hot pepper, ketchup, hoisin sauce, and sugar.
Mix together well and set aside.
STEP 2 - MARINATING THE CHICKEN
In a bowl, add the chicken, 1 pinch of salt, 1 pinch of white pepper, 2 egg whites, and 3 Tablespoon of corn starch
STEP 3 - DEEP FRY THE CHICKEN
Deep fry the chicken at 350 degrees for 3-4 minutes or until it is golden brown and loosen up the chicken so that they don't stick together.
Set the chicken aside.
STEP 4 - STIR FRY
Add the sauce to the wok and then the broccoli and wait until it is boiling.
To thicken the sauce, whisk together 2 Tablespoon of cornstarch and 4 Tablespoon of water in a bowl and slowly add to your stir-fry until it's the right thickness.
Next add in the chicken and stir-fry for a minute and serve on a plate`,
      strMealThumb:
        'https://www.themealdb.com/images/media/meals/1529444113.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=wWGwz0iBmvU',
      strIngredient1: 'Chicken Breast',
      strIngredient2: 'Plain Flour',
      strIngredient3: 'Egg',
      strIngredient4: 'Starch',
      strIngredient5: 'Baking Powder',
      strIngredient6: 'Salt',
      strIngredient7: 'Onion Salt',
      strIngredient8: 'Garlic Powder',
      strIngredient9: 'Water',
      strIngredient10: 'Chicken Stock',
      strIngredient11: 'Duck Sauce',
      strIngredient12: 'Soy Sauce',
      strIngredient13: 'Honey',
      strIngredient14: 'Rice Vinegar',
      strIngredient15: 'Sesame Seed Oil',
      strIngredient16: 'Gochujang',
      strIngredient17: 'Starch',
      strIngredient18: 'Garlic',
      strIngredient19: 'Spring Onions',
      strIngredient20: 'Ginger',
      strMeasure1: '1 1/2 ',
      strMeasure2: '3/4 cup ',
      strMeasure3: '1',
      strMeasure4: '2 tbs',
      strMeasure5: '1 tbs',
      strMeasure6: '1 tsp ',
      strMeasure7: '1/2 tsp',
      strMeasure8: '1/4 tsp',
      strMeasure9: '3/4 cup ',
      strMeasure10: '1/2 cup ',
      strMeasure11: '1/4 cup',
      strMeasure12: '3 tbs',
      strMeasure13: '2 tbs',
      strMeasure14: '1 tbs',
      strMeasure15: '2 tbs',
      strMeasure16: '1/2 tbs',
      strMeasure17: '2 tbs',
      strMeasure18: '1 clove',
      strMeasure19: '2 chopped',
      strMeasure20: '1 tsp ',
      strSource: 'https://www.skinnytaste.com/general-tsos-chicken/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    ingredients: [
      'Chicken Breast',
      'Plain Flour',
      'Egg',
      'Starch',
      'Baking Powder',
      'Salt',
      'Onion Salt',
      'Garlic Powder',
      'Water',
      'Chicken Stock',
      'Duck Sauce',
      'Soy Sauce',
      'Honey',
      'Rice Vinegar',
      'Sesame Seed Oil',
      'Gochujang',
      'Starch',
      'Garlic',
      'Spring Onions',
      'Ginger',
    ],
    userIngredientPresent: ['egg'],
    match: 5,
    nbrMissingIngredients: 19,
    measures: [
      '1 1/2 ',
      '3/4 cup ',
      '1',
      '2 tbs',
      '1 tbs',
      '1 tsp ',
      '1/2 tsp',
      '1/4 tsp',
      '3/4 cup ',
      '1/2 cup ',
      '1/4 cup',
      '3 tbs',
      '2 tbs',
      '1 tbs',
      '2 tbs',
      '1/2 tbs',
      '2 tbs',
      '1 clove',
      '2 chopped',
      '1 tsp ',
    ],
  },
  {
    strMeal: 'Katsu Chicken curry',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/vwrpps1503068729.jpg',
    idMeal: '52820',
    recipeDetail: {
      idMeal: '52820',
      strMeal: 'Katsu Chicken curry',
      strMealAlternate: null,
      strCategory: 'Chicken',
      strArea: 'Japanese',
      strInstructions: `Prep:15min  ›  Cook:30min  ›  Ready in:45min 

For the curry sauce: Heat oil in medium non-stick saucepan, add onion and garlic and cook until softened. Stir in carrots and cook over low heat for 10 to 12 minutes.
Add flour and curry powder; cook for 1 minute. Gradually stir in stock until combined; add honey, soy sauce and bay leaf. Slowly bring to the boil.
Turn down heat and simmer for 20 minutes or until sauce thickens but is still of pouring consistency. Stir in garam masala. Pour the curry sauce through a sieve; return to saucepan and keep on low heat until ready to serve.
For the chicken: Season both sides of chicken breasts with salt and pepper. Place flour, egg and breadcrumbs in separate bowls and arrange in a row. Coat the chicken breasts in flour, then dip them into the egg, then coat in breadcrumbs, making sure you cover both sides.
Heat oil in large frying pan over medium-high heat. Place chicken into hot oil and cook until golden brown, about 3 or 4 minutes each side. Once cooked, place on kitchen paper to absorb excess oil.
Pour curry sauce over chicken, serve with white rice and enjoy!`,
      strMealThumb:
        'https://www.themealdb.com/images/media/meals/vwrpps1503068729.jpg',
      strTags: 'Curry,Meat',
      strYoutube: 'https://www.youtube.com/watch?v=MWzxDFRtVbc',
      strIngredient1: 'chicken breast',
      strIngredient2: 'plain flour',
      strIngredient3: 'egg',
      strIngredient4: 'breadcrumbs',
      strIngredient5: 'vegetable oil',
      strIngredient6: 'sunflower oil',
      strIngredient7: 'onions',
      strIngredient8: 'garlic',
      strIngredient9: 'carrot',
      strIngredient10: 'plain flour',
      strIngredient11: 'curry powder',
      strIngredient12: 'chicken stock',
      strIngredient13: 'honey',
      strIngredient14: 'soy sauce',
      strIngredient15: 'bay leaf',
      strIngredient16: 'garam masala',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '4 pounded to 1cm thickness',
      strMeasure2: '2 tablespoons',
      strMeasure3: '1 beaten',
      strMeasure4: '100g fine',
      strMeasure5: '230ml frying',
      strMeasure6: '2 tablespoons',
      strMeasure7: '2 sliced',
      strMeasure8: '5 chopped cloves',
      strMeasure9: '2 sliced',
      strMeasure10: '2 tablespoons',
      strMeasure11: '4 teaspoons',
      strMeasure12: '600ml',
      strMeasure13: '2 teaspoons',
      strMeasure14: '4 teaspoons',
      strMeasure15: '1',
      strMeasure16: '1 teaspoon',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource:
        'http://allrecipes.co.uk/recipe/29578/chicken-katsu-curry.aspx',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    ingredients: [
      'chicken breast',
      'plain flour',
      'egg',
      'breadcrumbs',
      'vegetable oil',
      'sunflower oil',
      'onions',
      'garlic',
      'carrot',
      'plain flour',
      'curry powder',
      'chicken stock',
      'honey',
      'soy sauce',
      'bay leaf',
      'garam masala',
    ],
    userIngredientPresent: ['egg'],
    match: 6,
    nbrMissingIngredients: 15,
    measures: [
      '4 pounded to 1cm thickness',
      '2 tablespoons',
      '1 beaten',
      '100g fine',
      '230ml frying',
      '2 tablespoons',
      '2 sliced',
      '5 chopped cloves',
      '2 sliced',
      '2 tablespoons',
      '4 teaspoons',
      '600ml',
      '2 teaspoons',
      '4 teaspoons',
      '1',
      '1 teaspoon',
    ],
  },
  {
    strMeal: 'Mince Pies',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/qe8pf51576795532.jpg',
    idMeal: '52991',
    recipeDetail: {
      idMeal: '52991',
      strMeal: 'Mince Pies',
      strMealAlternate: null,
      strCategory: 'Dessert',
      strArea: 'British',
      strInstructions: `To make the pastry, rub 225g cold, diced butter into 350g plain flour, then mix in 100g golden caster sugar and a pinch of salt.

Combine the pastry into a ball – don’t add liquid – and knead it briefly. The dough will be fairly firm, like shortbread dough. You can use the dough immediately, or chill for later.

Preheat the oven to 200C/gas 6/fan 180C. Line 18 holes of two 12-hole patty tins, by pressing small walnut-sized balls of pastry into each hole.

Spoon 280g mincemeat into the pies.

Take slightly smaller balls of pastry than before and pat them out between your hands to make round lids, big enough to cover the pies. 

Top the pies with their lids, pressing the edges gently together to seal – you don’t need to seal them with milk or egg as they will stick on their own. (The pies may now be frozen for up to 1 month).

Beat 1 small egg and brush the tops of the pies. Bake for 20 mins until golden. Leave to cool in the tin for 5 mins, then remove to a wire rack.

To serve, lightly dust with icing sugar.`,
      strMealThumb:
        'https://www.themealdb.com/images/media/meals/qe8pf51576795532.jpg',
      strTags: 'Christmas',
      strYoutube: 'https://www.youtube.com/watch?v=PnXft7lQNJE',
      strIngredient1: 'Butter',
      strIngredient2: 'Plain Flour',
      strIngredient3: 'Caster Sugar',
      strIngredient4: 'Mincemeat',
      strIngredient5: 'Egg',
      strIngredient6: 'Icing Sugar',
      strIngredient7: '',
      strIngredient8: '',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '225g',
      strMeasure2: '350g',
      strMeasure3: '100g ',
      strMeasure4: '280g',
      strMeasure5: '1 small',
      strMeasure6: 'Topping',
      strMeasure7: ' ',
      strMeasure8: ' ',
      strMeasure9: ' ',
      strMeasure10: ' ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource:
        'https://www.bbcgoodfood.com/recipes/2174/unbelievably-easy-mince-pies',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    ingredients: [
      'Butter',
      'Plain Flour',
      'Caster Sugar',
      'Mincemeat',
      'Egg',
      'Icing Sugar',
    ],
    userIngredientPresent: ['egg'],
    match: 17,
    nbrMissingIngredients: 5,
    measures: ['225g', '350g', '100g ', '280g', '1 small', 'Topping'],
  },
  {
    strMeal: 'Moussaka',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/ctg8jd1585563097.jpg',
    idMeal: '53006',
    recipeDetail: {
      idMeal: '53006',
      strMeal: 'Moussaka',
      strMealAlternate: null,
      strCategory: 'Beef',
      strArea: 'Greek',
      strInstructions: `Heat the grill to high. Brown the beef in a deep ovenproof frying pan over a high heat for 5 mins. Meanwhile, prick the aubergine with a fork, then microwave on High for 3-5 mins until soft. Mix the yogurt, egg and parmesan together, then add a little seasoning.

Stir the tomatoes, purée and potatoes in with the beef with some seasoning and heat through. Smooth the surface of the beef mixture with the back of a spoon, then slice the cooked aubergine and arrange on top. Pour the yogurt mixture over the aubergines, smooth out evenly, then grill until the topping has set and turned golden.`,
      strMealThumb:
        'https://www.themealdb.com/images/media/meals/ctg8jd1585563097.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=8U_29i9Qp5U',
      strIngredient1: 'Beef',
      strIngredient2: 'Aubergine',
      strIngredient3: 'Greek Yogurt',
      strIngredient4: 'Egg',
      strIngredient5: 'Parmesan',
      strIngredient6: 'Tomato',
      strIngredient7: 'Tomato Puree',
      strIngredient8: 'Potatoes',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '500g',
      strMeasure2: '1 large',
      strMeasure3: '150g',
      strMeasure4: '1 beaten',
      strMeasure5: '3 tbs',
      strMeasure6: '400g',
      strMeasure7: '4 tbs',
      strMeasure8: '350g',
      strMeasure9: ' ',
      strMeasure10: ' ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://www.bbcgoodfood.com/recipes/must-make-moussaka',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    ingredients: [
      'Beef',
      'Aubergine',
      'Greek Yogurt',
      'Egg',
      'Parmesan',
      'Tomato',
      'Tomato Puree',
      'Potatoes',
    ],
    userIngredientPresent: ['egg'],
    match: 13,
    nbrMissingIngredients: 7,
    measures: [
      '500g',
      '1 large',
      '150g',
      '1 beaten',
      '3 tbs',
      '400g',
      '4 tbs',
      '350g',
    ],
  },
  {
    strMeal: 'Nanaimo Bars',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/vwuprt1511813703.jpg',
    idMeal: '52924',
    recipeDetail: {
      idMeal: '52924',
      strMeal: 'Nanaimo Bars',
      strMealAlternate: null,
      strCategory: 'Dessert',
      strArea: 'Canadian',
      strInstructions: `Start by making the biscuit base. In a bowl, over a pan of simmering water, melt the butter with the sugar and cocoa powder, stirring occasionally until smooth. Whisk in the egg for 2 to 3 mins until the mixture has thickened. Remove from heat and mix in the biscuit crumbs, coconut and almonds if using, then press into the base of a lined 20cm square tin. Chill for 10 mins.
For the middle layer, make the custard icing; whisk together the butter, cream and custard powder until light and fluffy, then gradually add the icing sugar until fully incorporated. Spread over the bottom layer and chill in the fridge for at least 10 mins until the custard is no longer soft.
Melt the chocolate and butter together in the microwave, then spread over the chilled bars and put back in the fridge. Leave until the chocolate has fully set (about 2 hrs). Take the mixture out of the tin and slice into squares to serve.`,
      strMealThumb:
        'https://www.themealdb.com/images/media/meals/vwuprt1511813703.jpg',
      strTags: 'Treat,Snack,Dairy',
      strYoutube: 'https://www.youtube.com/watch?v=MMrE4I1ZtWo',
      strIngredient1: 'Custard',
      strIngredient2: 'Caster Sugar',
      strIngredient3: 'Cocoa',
      strIngredient4: 'Egg',
      strIngredient5: 'Digestive Biscuits',
      strIngredient6: 'Desiccated Coconut',
      strIngredient7: 'Almonds',
      strIngredient8: 'Butter',
      strIngredient9: 'Double Cream',
      strIngredient10: 'Custard Powder',
      strIngredient11: 'Icing Sugar',
      strIngredient12: 'Dark Chocolate',
      strIngredient13: 'Butter',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '125g',
      strMeasure2: '50g',
      strMeasure3: '5 tbs',
      strMeasure4: '1 beaten',
      strMeasure5: '200g shredded',
      strMeasure6: '100g ',
      strMeasure7: '50g',
      strMeasure8: '100g ',
      strMeasure9: '4 tbs',
      strMeasure10: '3 tbs',
      strMeasure11: '250g',
      strMeasure12: '150g',
      strMeasure13: '50g',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'https://www.bbcgoodfood.com/recipes/nanaimo-bars',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    ingredients: [
      'Custard',
      'Caster Sugar',
      'Cocoa',
      'Egg',
      'Digestive Biscuits',
      'Desiccated Coconut',
      'Almonds',
      'Butter',
      'Double Cream',
      'Custard Powder',
      'Icing Sugar',
      'Dark Chocolate',
      'Butter',
    ],
    userIngredientPresent: ['egg'],
    match: 8,
    nbrMissingIngredients: 12,
    measures: [
      '125g',
      '50g',
      '5 tbs',
      '1 beaten',
      '200g shredded',
      '100g ',
      '50g',
      '100g ',
      '4 tbs',
      '3 tbs',
      '250g',
      '150g',
      '50g',
    ],
  },
  {
    strMeal: 'Parkin Cake',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/qxuqtt1511724269.jpg',
    idMeal: '52902',
    recipeDetail: {
      idMeal: '52902',
      strMeal: 'Parkin Cake',
      strMealAlternate: null,
      strCategory: 'Dessert',
      strArea: 'British',
      strInstructions: `Heat oven to 160C/140C fan/gas 3. Grease a deep 22cm/9in square cake tin and line with baking parchment. Beat the egg and milk together with a fork.

Gently melt the syrup, treacle, sugar and butter together in a large pan until the sugar has dissolved. Remove from the heat. Mix together the oatmeal, flour and ginger and stir into the syrup mixture, followed by the egg and milk.

Pour the mixture into the tin and bake for 50 mins - 1 hr until the cake feels firm and a little crusty on top. Cool in the tin then wrap in more parchment and foil and keep for 3-5 days before eating if you can – it’ll become softer and stickier the longer you leave it, up to 2 weeks.
`,
      strMealThumb:
        'https://www.themealdb.com/images/media/meals/qxuqtt1511724269.jpg',
      strTags: 'Caramel',
      strYoutube: 'https://www.youtube.com/watch?v=k1lG4vk2MQA',
      strIngredient1: 'Butter',
      strIngredient2: 'Egg',
      strIngredient3: 'Milk',
      strIngredient4: 'Golden Syrup',
      strIngredient5: 'Black Treacle',
      strIngredient6: 'Brown Sugar',
      strIngredient7: 'Oatmeal',
      strIngredient8: 'Self-raising Flour',
      strIngredient9: 'Ground Ginger',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '200g',
      strMeasure2: '1 large',
      strMeasure3: '4 tbs',
      strMeasure4: '200g',
      strMeasure5: '85g',
      strMeasure6: '85g',
      strMeasure7: '100g ',
      strMeasure8: '250g',
      strMeasure9: '1 tbs',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'https://www.bbcgoodfood.com/recipes/1940684/parkin',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    ingredients: [
      'Butter',
      'Egg',
      'Milk',
      'Golden Syrup',
      'Black Treacle',
      'Brown Sugar',
      'Oatmeal',
      'Self-raising Flour',
      'Ground Ginger',
    ],
    userIngredientPresent: ['egg'],
    match: 11,
    nbrMissingIngredients: 8,
    measures: [
      '200g',
      '1 large',
      '4 tbs',
      '200g',
      '85g',
      '85g',
      '100g ',
      '250g',
      '1 tbs',
    ],
  },
  {
    strMeal: 'Paszteciki (Polish Pasties)',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/c9a3l31593261890.jpg',
    idMeal: '53017',
    recipeDetail: {
      idMeal: '53017',
      strMeal: 'Paszteciki (Polish Pasties)',
      strMealAlternate: null,
      strCategory: 'Beef',
      strArea: 'Polish',
      strInstructions: `Sift flour and salt into a large mixing bowl.
Use a spoon to push the egg yolk through a fine sieve into the flour.
Add the raw egg and mix well.
Beat in butter 1 tablespoon at a time.
Place dough on a floured surface and knead until smooth and elastic, then wrap in waxed paper and refrigerate until firm (at least 30 minutes).
In a heavy skillet, melt 2 tablespoons butter over medium heat; saute the onion and rutabaga until the onion is soft and transparent (5 minutes).
Put the onions, rutabaga, and beef through a meat grinder twice if you have one, if not just chop them up as fine as possible.
Melt the remaining 4 tablespoons butter over medium heat, and add the meat mixture.
Cook over low heat, stirring occasionally, until all of the liquid has evaporated and the mixture is thick enough to hold its shape.
Remove from heat and let cool, then stir in 1 egg, and season with salt and pepper.
Preheat oven to 350°F.
On a lightly floured surface, roll the dough out into a 13x8" rectangle (1/8" thick).
Spoon the filling down the center of the rectangle lengthwise, leaving about an inch of space on each end.
Lightly brush the long sides with cold water, then fold one of the long sides over the filling and the other side over the top of that.
Brush the short ends with cold water and fold them over the top, enclosing the filling.
Place pastry seam side down on a baking sheet and brush the top evenly with the remaining scrambled egg.
Bake in preheated oven until rich golden brown (30 minutes).
Slice pastry diagonally into 1.5" long pieces and serve as an appetizer or with soup.`,
      strMealThumb:
        'https://www.themealdb.com/images/media/meals/c9a3l31593261890.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=qANmR6BBJpQ',
      strIngredient1: 'Flour',
      strIngredient2: 'Salt',
      strIngredient3: 'Egg',
      strIngredient4: 'Egg',
      strIngredient5: 'Butter',
      strIngredient6: 'Butter',
      strIngredient7: 'Onion',
      strIngredient8: 'Swede',
      strIngredient9: 'Beef Brisket',
      strIngredient10: 'Eggs',
      strIngredient11: 'Salt',
      strIngredient12: 'Pepper',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1 cup ',
      strMeasure2: '1/4 tsp',
      strMeasure3: '1 Yolk',
      strMeasure4: '1',
      strMeasure5: '5 tbs',
      strMeasure6: '6 tblsp',
      strMeasure7: '1/3 cup',
      strMeasure8: '1/2 cup ',
      strMeasure9: '1/2 lb',
      strMeasure10: '2 Beaten ',
      strMeasure11: '1 tsp ',
      strMeasure12: '1/4 tsp',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://www.food.com/recipe/paszteciki-polish-pasties-117909',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    ingredients: [
      'Flour',
      'Salt',
      'Egg',
      'Egg',
      'Butter',
      'Butter',
      'Onion',
      'Swede',
      'Beef Brisket',
      'Eggs',
      'Salt',
      'Pepper',
    ],
    userIngredientPresent: ['egg'],
    match: 8,
    nbrMissingIngredients: 11,
    measures: [
      '1 cup ',
      '1/4 tsp',
      '1 Yolk',
      '1',
      '5 tbs',
      '6 tblsp',
      '1/3 cup',
      '1/2 cup ',
      '1/2 lb',
      '2 Beaten ',
      '1 tsp ',
      '1/4 tsp',
    ],
  },
  {
    strMeal: 'Peanut Butter Cookies',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/1544384070.jpg',
    idMeal: '52958',
    recipeDetail: {
      idMeal: '52958',
      strMeal: 'Peanut Butter Cookies',
      strMealAlternate: null,
      strCategory: 'Dessert',
      strArea: 'American',
      strInstructions: `Preheat oven to 350ºF (180ºC).
In a large bowl, mix together the peanut butter, sugar, and egg.
Scoop out a spoonful of dough and roll it into a ball. Place the cookie balls onto a nonstick baking sheet.
For extra decoration and to make them cook more evenly, flatten the cookie balls by pressing a fork down on top of them, then press it down again at a 90º angle to make a criss-cross pattern.
Bake for 8-10 minutes or until the bottom of the cookies are golden brown.
Remove from baking sheet and cool.
Enjoy!`,
      strMealThumb:
        'https://www.themealdb.com/images/media/meals/1544384070.jpg',
      strTags: 'Breakfast,UnHealthy,BBQ',
      strYoutube: '',
      strIngredient1: 'Peanut Butter',
      strIngredient2: 'Sugar',
      strIngredient3: 'Egg',
      strIngredient4: '',
      strIngredient5: '',
      strIngredient6: '',
      strIngredient7: '',
      strIngredient8: '',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1 cup ',
      strMeasure2: '1/2 cup ',
      strMeasure3: '1',
      strMeasure4: '',
      strMeasure5: '',
      strMeasure6: '',
      strMeasure7: '',
      strMeasure8: '',
      strMeasure9: '',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'https://tasty.co/recipe/3-ingredient-peanut-butter-cookies',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    ingredients: ['Peanut Butter', 'Sugar', 'Egg'],
    userIngredientPresent: ['egg'],
    match: 33,
    nbrMissingIngredients: 2,
    measures: ['1 cup ', '1/2 cup ', '1'],
  },
  {
    strMeal: 'Salmon Eggs Eggs Benedict',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/1550440197.jpg',
    idMeal: '52962',
    recipeDetail: {
      idMeal: '52962',
      strMeal: 'Salmon Eggs Eggs Benedict',
      strMealAlternate: null,
      strCategory: 'Breakfast',
      strArea: 'American',
      strInstructions: `First make the Hollandaise sauce. Put the lemon juice and vinegar in a small bowl, add the egg yolks and whisk with a balloon whisk until light and frothy. Place the bowl over a pan of simmering water and whisk until mixture thickens. Gradually add the butter, whisking constantly until thick – if it looks like it might be splitting, then whisk off the heat for a few mins. Season and keep warm.

To poach the eggs, bring a large pan of water to the boil and add the vinegar. Lower the heat so that the water is simmering gently. Stir the water so you have a slight whirlpool, then slide in the eggs one by one. Cook each for about 4 mins, then remove with a slotted spoon.

Lightly toast and butter the muffins, then put a couple of slices of salmon on each half. Top each with an egg, spoon over some Hollandaise and garnish with chopped chives.`,
      strMealThumb:
        'https://www.themealdb.com/images/media/meals/1550440197.jpg',
      strTags: 'Bun,Brunch',
      strYoutube: 'https://www.youtube.com/watch?v=Woiiet4vQ58',
      strIngredient1: 'Eggs',
      strIngredient2: 'White Wine Vinegar',
      strIngredient3: 'English Muffins',
      strIngredient4: 'Butter',
      strIngredient5: 'Smoked Salmon',
      strIngredient6: 'Lemon Juice',
      strIngredient7: 'White Wine Vinegar',
      strIngredient8: 'Egg',
      strIngredient9: 'Unsalted Butter',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '4',
      strMeasure2: '2 tbs',
      strMeasure3: '2',
      strMeasure4: 'To serve',
      strMeasure5: '8 slices',
      strMeasure6: '2 tsp',
      strMeasure7: '2 tsp',
      strMeasure8: '3 Yolkes',
      strMeasure9: '125g',
      strMeasure10: ' ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource:
        'https://www.bbcgoodfood.com/recipes/73606/eggs-benedict-with-smoked-salmon-and-chives',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    ingredients: [
      'Eggs',
      'White Wine Vinegar',
      'English Muffins',
      'Butter',
      'Smoked Salmon',
      'Lemon Juice',
      'White Wine Vinegar',
      'Egg',
      'Unsalted Butter',
    ],
    userIngredientPresent: ['egg'],
    match: 11,
    nbrMissingIngredients: 8,
    measures: [
      '4',
      '2 tbs',
      '2',
      'To serve',
      '8 slices',
      '2 tsp',
      '2 tsp',
      '3 Yolkes',
      '125g',
    ],
  },
  {
    strMeal: 'Shrimp Chow Fun',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/1529445434.jpg',
    idMeal: '52953',
    recipeDetail: {
      idMeal: '52953',
      strMeal: 'Shrimp Chow Fun',
      strMealAlternate: null,
      strCategory: 'Seafood',
      strArea: 'Chinese',
      strInstructions: `STEP 1 - SOAK THE RICE NOODLES
Soak the rice noodles overnight untill they are soft
STEP 2 - BOIL THE RICE NOODLES
Boil the noodles for 10-15 minutes and then rinse with cold water to stop the cooking process of the noodles.
STEP 3 -MARINATING THE SHRIMP
In a bowl add the shrimp, egg, 1 pinch of white pepper, 1 Teaspoon of sesame seed oil, 1 Tablespoon corn starch and 1 tablespoon of oil
Mix together well
STEP 4 - STIR FRY
In a wok add 2 Tablespoons of oil, shrimp and stir fry them until it is golden brown
Set the shrimp aside
Add 1 Tablespoon of oil to the work and then add minced garlic, ginger and all of the vegetables.
Add the noodles to the wok
Next add sherry cooking wine, oyster sauce, sugar, vinegar, sesame seed oil, 1 pinch white pepper, and soy sauce
Add back in the shrimp
To thicken the sauce, whisk together 1 Tablespoon of corn starch and 2 Tablespoon of water in a bowl and slowly add to your stir-fry until it's the right thickness.`,
      strMealThumb:
        'https://www.themealdb.com/images/media/meals/1529445434.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=wzaTcpoFEaY',
      strIngredient1: 'Rice Stick Noodles',
      strIngredient2: 'Prawns',
      strIngredient3: 'Egg',
      strIngredient4: 'Pepper',
      strIngredient5: 'Sesame Seed Oil',
      strIngredient6: 'Cornstarch',
      strIngredient7: 'Oil',
      strIngredient8: 'Minced Garlic',
      strIngredient9: 'Ginger',
      strIngredient10: 'Onion',
      strIngredient11: 'Bean Sprouts',
      strIngredient12: 'Spring Onions',
      strIngredient13: 'Cooking wine',
      strIngredient14: 'Oyster Sauce',
      strIngredient15: 'Sugar',
      strIngredient16: 'Vinegar',
      strIngredient17: 'Soy Sauce',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1/2 bag',
      strMeasure2: '8 oz ',
      strMeasure3: '1/2 ',
      strMeasure4: 'pinch',
      strMeasure5: '2 tsp',
      strMeasure6: '2 tbs',
      strMeasure7: '4 tbs',
      strMeasure8: '1 tsp ',
      strMeasure9: '1 tsp ',
      strMeasure10: '1/2 cup ',
      strMeasure11: '1 cup ',
      strMeasure12: '1/2 cup ',
      strMeasure13: '1 tbs',
      strMeasure14: '1 tbs',
      strMeasure15: '1/2 tbs',
      strMeasure16: '1/2 tbs',
      strMeasure17: '1 tbs',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'https://sueandgambo.com/pages/shrimp-chow-fun',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    ingredients: [
      'Rice Stick Noodles',
      'Prawns',
      'Egg',
      'Pepper',
      'Sesame Seed Oil',
      'Cornstarch',
      'Oil',
      'Minced Garlic',
      'Ginger',
      'Onion',
      'Bean Sprouts',
      'Spring Onions',
      'Cooking wine',
      'Oyster Sauce',
      'Sugar',
      'Vinegar',
      'Soy Sauce',
    ],
    userIngredientPresent: ['egg'],
    match: 6,
    nbrMissingIngredients: 16,
    measures: [
      '1/2 bag',
      '8 oz ',
      '1/2 ',
      'pinch',
      '2 tsp',
      '2 tbs',
      '4 tbs',
      '1 tsp ',
      '1 tsp ',
      '1/2 cup ',
      '1 cup ',
      '1/2 cup ',
      '1 tbs',
      '1 tbs',
      '1/2 tbs',
      '1/2 tbs',
      '1 tbs',
    ],
  },
  {
    strMeal: 'Spring onion and prawn empanadas',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/1c5oso1614347493.jpg',
    idMeal: '53040',
    recipeDetail: {
      idMeal: '53040',
      strMeal: 'Spring onion and prawn empanadas',
      strMealAlternate: null,
      strCategory: 'Seafood',
      strArea: 'Portuguese',
      strInstructions: `STEP 1

To make the dough, rub the butter into the flour and then add the egg white and half the yolk (keep the rest), vinegar, a pinch of salt and enough cold water to make a soft dough. Knead on a floured surface until smooth and then wrap and rest for 30 minutes.

STEP 2

Heat the oven to 180c/fan 160c/gas 4. Trim the green ends of the spring onions and then finely slice the rest. Heat a little oil in a pan and fry them gently until soft but not browned. Add the chilli and garlic, stir and then add the prawns and cook until they are opaque. Season well. Scoop out the prawns and bubble the juices until they thicken, then add back the prawns.

STEP 3

Divide the empanada dough into eight balls and roll out to thin circles on a floured surface. Put some filling on one half of the dough, sprinkle the feta on top and fold the other half over. Trim the edge and then fold and crimp the dough together so the empanada is tightly sealed, put it on an oiled baking sheet either on its side or sitting on its un-crimped edge like a cornish pasty. Repeat with the remaining dough and mixture. Mix the leftover egg yolk with a splash of water and brush the top of the empanadas.

STEP 4

Bake for 30 minutes or until golden and slightly crisp around the edges.`,
      strMealThumb:
        'https://www.themealdb.com/images/media/meals/1c5oso1614347493.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=Q24haJU-1dI',
      strIngredient1: 'Spring Onions',
      strIngredient2: 'Olive Oil',
      strIngredient3: 'Red Chilli',
      strIngredient4: 'Garlic',
      strIngredient5: 'Prawns',
      strIngredient6: 'Feta',
      strIngredient7: 'Butter',
      strIngredient8: 'Plain Flour',
      strIngredient9: 'Egg',
      strIngredient10: 'White Wine Vinegar',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1  bunch',
      strMeasure2: 'Dash',
      strMeasure3: '1 finely sliced',
      strMeasure4: '1 clove',
      strMeasure5: '350g',
      strMeasure6: '75g',
      strMeasure7: '15g',
      strMeasure8: '250g',
      strMeasure9: '1 Seperated',
      strMeasure10: '1/2 tsp',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource:
        'https://www.olivemagazine.com/recipes/fish-and-seafood/spring-onion-and-prawn-empanadas/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    ingredients: [
      'Spring Onions',
      'Olive Oil',
      'Red Chilli',
      'Garlic',
      'Prawns',
      'Feta',
      'Butter',
      'Plain Flour',
      'Egg',
      'White Wine Vinegar',
    ],
    userIngredientPresent: ['egg'],
    match: 10,
    nbrMissingIngredients: 9,
    measures: [
      '1  bunch',
      'Dash',
      '1 finely sliced',
      '1 clove',
      '350g',
      '75g',
      '15g',
      '250g',
      '1 Seperated',
      '1/2 tsp',
    ],
  },
  {
    strMeal: 'Sweet and Sour Pork',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/1529442316.jpg',
    idMeal: '52949',
    recipeDetail: {
      idMeal: '52949',
      strMeal: 'Sweet and Sour Pork',
      strMealAlternate: null,
      strCategory: 'Pork',
      strArea: 'Chinese',
      strInstructions: `Preparation
1. Crack the egg into a bowl. Separate the egg white and yolk.

Sweet and Sour Pork
2. Slice the pork tenderloin into strips.

3. Prepare the marinade using a pinch of salt, one teaspoon of starch, two teaspoons of light soy sauce, and an egg white.

4. Marinade the pork strips for about 20 minutes.

5. Put the remaining starch in a bowl. Add some water and vinegar to make a starchy sauce.

Sweet and Sour Pork
Cooking Instructions
1. Pour the cooking oil into a wok and heat to 190°C (375°F). Add the marinated pork strips and fry them until they turn brown. Remove the cooked pork from the wok and place on a plate.

2. Leave some oil in the wok. Put the tomato sauce and white sugar into the wok, and heat until the oil and sauce are fully combined.

3. Add some water to the wok and thoroughly heat the sweet and sour sauce before adding the pork strips to it.

4. Pour in the starchy sauce. Stir-fry all the ingredients until the pork and sauce are thoroughly mixed together.

5. Serve on a plate and add some coriander for decoration.`,
      strMealThumb:
        'https://www.themealdb.com/images/media/meals/1529442316.jpg',
      strTags: 'Sweet',
      strYoutube: 'https://www.youtube.com/watch?v=mdaBIhgEAMo',
      strIngredient1: 'Pork',
      strIngredient2: 'Egg',
      strIngredient3: 'Water',
      strIngredient4: 'Salt',
      strIngredient5: 'Sugar',
      strIngredient6: 'Soy Sauce',
      strIngredient7: 'Starch',
      strIngredient8: 'Tomato Puree',
      strIngredient9: 'Vinegar',
      strIngredient10: 'Coriander',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '200g',
      strMeasure2: '1',
      strMeasure3: 'Dash',
      strMeasure4: '1/2 tsp',
      strMeasure5: '1 tsp ',
      strMeasure6: '10g',
      strMeasure7: '10g',
      strMeasure8: '30g',
      strMeasure9: '10g',
      strMeasure10: 'Dash',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource:
        'https://www.chinahighlights.com/travelguide/chinese-food/cooking/sweet-sour-pork.htm',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    ingredients: [
      'Pork',
      'Egg',
      'Water',
      'Salt',
      'Sugar',
      'Soy Sauce',
      'Starch',
      'Tomato Puree',
      'Vinegar',
      'Coriander',
    ],
    userIngredientPresent: ['egg'],
    match: 10,
    nbrMissingIngredients: 9,
    measures: [
      '200g',
      '1',
      'Dash',
      '1/2 tsp',
      '1 tsp ',
      '10g',
      '10g',
      '30g',
      '10g',
      'Dash',
    ],
  },
  {
    strMeal: 'Timbits',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/txsupu1511815755.jpg',
    idMeal: '52929',
    recipeDetail: {
      idMeal: '52929',
      strMeal: 'Timbits',
      strMealAlternate: null,
      strCategory: 'Dessert',
      strArea: 'Canadian',
      strInstructions: `Sift together dry ingredients.
Mix together wet ingredients and incorporate into dry. Stir until smooth.
Drop by teaspoonfuls(no bigger) into hot oil (365 degrees, no hotter), turning after a few moments until golden brown on all sides.
Remove and drain.
Roll in cinnamon sugar while still warm and serve.`,
      strMealThumb:
        'https://www.themealdb.com/images/media/meals/txsupu1511815755.jpg',
      strTags: 'Snack,Treat',
      strYoutube: 'https://www.youtube.com/watch?v=fFLn1h80AGQ',
      strIngredient1: 'Flour',
      strIngredient2: 'Sugar',
      strIngredient3: 'Baking Powder',
      strIngredient4: 'Salt',
      strIngredient5: 'Egg',
      strIngredient6: 'Milk',
      strIngredient7: 'Oil',
      strIngredient8: 'Oil',
      strIngredient9: 'Icing Sugar',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '2 cups ',
      strMeasure2: '1/3 cup',
      strMeasure3: '3 tsp',
      strMeasure4: '½ tsp',
      strMeasure5: '1 beaten',
      strMeasure6: '¾ cup',
      strMeasure7: '3 tbs',
      strMeasure8: 'for frying',
      strMeasure9: 'garnish',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'http://www.geniuskitchen.com/recipe/drop-doughnuts-133877',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    ingredients: [
      'Flour',
      'Sugar',
      'Baking Powder',
      'Salt',
      'Egg',
      'Milk',
      'Oil',
      'Oil',
      'Icing Sugar',
    ],
    userIngredientPresent: ['egg'],
    match: 11,
    nbrMissingIngredients: 8,
    measures: [
      '2 cups ',
      '1/3 cup',
      '3 tsp',
      '½ tsp',
      '1 beaten',
      '¾ cup',
      '3 tbs',
      'for frying',
      'garnish',
    ],
  },
  {
    strMeal: 'Tourtiere',
    strMealThumb:
      'https://www.themealdb.com/images/media/meals/ytpstt1511814614.jpg',
    idMeal: '52926',
    recipeDetail: {
      idMeal: '52926',
      strMeal: 'Tourtiere',
      strMealAlternate: null,
      strCategory: 'Pork',
      strArea: 'Canadian',
      strInstructions: `Heat oven to 200C/180C fan/gas 6. Boil the potato until tender, drain and mash, then leave to cool. Heat the oil in a non-stick pan, add the mince and onion and quickly fry until browned. Add the garlic, spices, stock, plenty of pepper and a little salt and mix well. Remove from the heat, stir into the potato and leave to cool.
Roll out half the pastry and line the base of a 20-23cm pie plate or flan tin. Fill with the pork mixture and brush the edges of the pastry with water. Roll out the remaining dough and cover the pie. Press the edges of the pastry to seal, trimming off the excess. Prick the top of the pastry case to allow steam to escape and glaze the top with the beaten egg.
Bake for 30 mins until the pastry is crisp and golden. Serve cut into wedges with a crisp green salad. Leftovers are good cold for lunch the next day, served with a selection of pickles.`,
      strMealThumb:
        'https://www.themealdb.com/images/media/meals/ytpstt1511814614.jpg',
      strTags: 'Pie,MainMeal,BBQ,Cake',
      strYoutube: 'https://www.youtube.com/watch?v=A96hbwobKKs',
      strIngredient1: 'Potatoes',
      strIngredient2: 'Sunflower Oil',
      strIngredient3: 'Minced Pork',
      strIngredient4: 'Onion',
      strIngredient5: 'Garlic Clove',
      strIngredient6: 'Cinnamon',
      strIngredient7: 'Allspice',
      strIngredient8: 'Nutmeg',
      strIngredient9: 'Vegetable Stock',
      strIngredient10: 'Shortcrust Pastry',
      strIngredient11: 'Egg',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1 medium',
      strMeasure2: '1 tsp ',
      strMeasure3: '500g',
      strMeasure4: '1 finely chopped ',
      strMeasure5: '1 finely chopped ',
      strMeasure6: '¼ tsp',
      strMeasure7: '¼ tsp',
      strMeasure8: '¼ tsp',
      strMeasure9: '100ml',
      strMeasure10: '400g',
      strMeasure11: 'To Glaze',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource:
        'https://www.bbcgoodfood.com/recipes/531644/spiced-pork-and-potato-pie',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    ingredients: [
      'Potatoes',
      'Sunflower Oil',
      'Minced Pork',
      'Onion',
      'Garlic Clove',
      'Cinnamon',
      'Allspice',
      'Nutmeg',
      'Vegetable Stock',
      'Shortcrust Pastry',
      'Egg',
    ],
    userIngredientPresent: ['egg'],
    match: 9,
    nbrMissingIngredients: 10,
    measures: [
      '1 medium',
      '1 tsp ',
      '500g',
      '1 finely chopped ',
      '1 finely chopped ',
      '¼ tsp',
      '¼ tsp',
      '¼ tsp',
      '100ml',
      '400g',
      'To Glaze',
    ],
  },
].sort((a, b) => b.match - a.match);

export default function Page() {
  const { recipes, hasSearched } = useFood();

  return (
    <div
      className=" flex  flex-col   items-center
   
    
    bg-[url('/food.jpg')] bg-cover h-[calc(100dvh-var(--header-height))]  overflow-auto"
    >
      <div className="card   bg-base-100 max-w-[550px] rounded-2xl shadow-lg h-fit flex flex-col  gap-5 m-4  p-3">
        <h1 className="font-bold text-4xl ">My Pantry</h1>
        <p className="">
          Add ingredients you already have and we&#39;ll find recipes that
          match.
        </p>
        <AddIngredient />
      </div>
      {hasSearched && <Carousel elements={elements} />}
      {/*       {hasSearched && <RecipesList recipes={recipes}/> }
       */}{' '}
      <Footer>
        <FetchRecipes />
      </Footer>
    </div>
  );
}
