import { FoodProvider } from '@/components/food-provider';
import Header from '@/components/header';
import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import './globals.css';
import { Suspense } from 'react';
import Loading from './loading';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <FoodProvider>
            <div className="flex min-h-screen flex-col">
              <Header />
              <main className="flex-2 overflow-y-auto">
                <Suspense fallback={<Loading />}>{children}</Suspense>
              </main>
            </div>
          </FoodProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
