import type { Metadata } from "next";
import "./globals.css";
import { FoodProvider } from "@/components/food-provider";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <FoodProvider>
        <body className="antialiased w-screen h-screen flex items-center justify-center">
          <ThemeProvider>{children}</ThemeProvider>
        </body>
      </FoodProvider>
    </html>
  );
}
