import { FoodProvider } from '@/components/food-provider';
import Header from '@/components/header';
import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <FoodProvider>
          <ThemeProvider>
            <div className="flex max-h-full max-w-screen flex-col">
              <Header />
              {children}
            </div>
          </ThemeProvider>
        </FoodProvider>
      </body>
    </html>
  );
}
